POST http://localhost:5000/fragility/data HTTP/1.1
Content-Type: application/json
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

{
    "pageSize": 1000,
    "pageIndex": 1,
    "scoreMinValue": null,
    "scoreMaxValue": null,
    "referencePoint": 2,
    "region": {
        "data": null,
        "exclude": true
    },
    "department": {
        "data": null,
        "exclude": false
    },
    "intercommnality": {
        "data": null,
        "exclude": true
    },
    "commune": {
        "data": null,
        "exclude": false
    }
    
}



### Filter Data
GET  http://localhost:5000/fragility/filterdata HTTP/1.1
Content-Type: application/json
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

###
GET  http://146.59.227.253/fragility/filterdata HTTP/1.1


### server api
POST http://146.59.227.253/fragility/data HTTP/1.1
Content-Type: application/json
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

{
    "pageSize": 100,
    "pageIndex": 1,
    "region": {
        "data": null,
        "exclude": true
    },
    "department": {
        "data": null,
        "exclude": false
    }
    
}

### 
POST http://146.59.227.253:3000/datas HTTP/1.1
Content-Type: application/json
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

{
  "criteria": {
    "referencePoint": "ALL",
    "scoreMinValue": "",
    "scoreMaxValue": "",
    "calcul": true,
    "pageIndex": 0,
    "pageSize": 100
  }
}