POST http://localhost:5000/fragility/data HTTP/1.1
Content-Type: application/json
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

{
    "pageSize": 100
}



### Filter Data
GET  http://localhost:5000/fragility/filterdata HTTP/1.1
Content-Type: application/json
Accept: application/json
Accept-Encoding: br, gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

